"$schema" = "./node_modules/wrangler/config-schema.json"
name = "cdn-padow-ru"
main = "src/index.ts"
compatibility_date = "2026-05-29"
workers_dev = false

[assets]
directory = "./public"
binding = "ASSETS"
